/**
 * Seed data for categories, products and stores (MVP demo).
 * ALDI-typical categories and sample products for search.
 */

import type { Category, Product, Store } from "@/types";

function now(): string {
  return new Date().toISOString();
}

export const SEED_CATEGORIES: Category[] = [
  {
    category_id: "cat-obst-gemuese",
    name: "Obst & Gemüse",
    name_translations: { de: "Obst & Gemüse", en: "Fruit & Vegetables" },
    icon: "🍎",
    default_sort_position: 1,
  },
  {
    category_id: "cat-brot",
    name: "Brot & Backwaren",
    name_translations: { de: "Brot & Backwaren", en: "Bread & Bakery" },
    icon: "🍞",
    default_sort_position: 2,
  },
  {
    category_id: "cat-milch",
    name: "Milchprodukte",
    name_translations: { de: "Milchprodukte", en: "Dairy" },
    icon: "🥛",
    default_sort_position: 3,
  },
  {
    category_id: "cat-fleisch",
    name: "Fleisch & Wurst",
    name_translations: { de: "Fleisch & Wurst", en: "Meat & Sausage" },
    icon: "🥩",
    default_sort_position: 4,
  },
  {
    category_id: "cat-tiefkuehl",
    name: "Tiefkühl",
    name_translations: { de: "Tiefkühl", en: "Frozen" },
    icon: "🧊",
    default_sort_position: 5,
  },
  {
    category_id: "cat-getraenke",
    name: "Getränke",
    name_translations: { de: "Getränke", en: "Beverages" },
    icon: "🥤",
    default_sort_position: 6,
  },
  {
    category_id: "cat-suess",
    name: "Süßwaren & Snacks",
    name_translations: { de: "Süßwaren & Snacks", en: "Sweets & Snacks" },
    icon: "🍫",
    default_sort_position: 7,
  },
  {
    category_id: "cat-grundnahrung",
    name: "Grundnahrungsmittel",
    name_translations: { de: "Grundnahrungsmittel", en: "Staples" },
    icon: "🍚",
    default_sort_position: 8,
  },
  {
    category_id: "cat-haushalt",
    name: "Haushalt & Reinigung",
    name_translations: { de: "Haushalt & Reinigung", en: "Household" },
    icon: "🧹",
    default_sort_position: 9,
  },
  {
    category_id: "cat-sonstiges",
    name: "Sonstiges",
    name_translations: { de: "Sonstiges", en: "Other" },
    icon: "📦",
    default_sort_position: 10,
  },
];

/** Demo stores for F04 (GPS radius ~50–100m). Coordinates are example values. */
export const SEED_STORES: Store[] = [
  {
    store_id: "store-aldi-musterstr",
    name: "ALDI SÜD Musterstraße",
    address: "Musterstraße 12, 40215 Düsseldorf",
    city: "Düsseldorf",
    postal_code: "40215",
    country: "DE",
    latitude: 51.2277,
    longitude: 6.7735,
    has_sorting_data: false,
    sorting_data_quality: 0,
    created_at: now(),
    updated_at: now(),
  },
  {
    store_id: "store-aldi-konrad",
    name: "ALDI SÜD Konrad-Adenauer-Platz",
    address: "Konrad-Adenauer-Platz 1, 40210 Düsseldorf",
    city: "Düsseldorf",
    postal_code: "40210",
    country: "DE",
    latitude: 51.2189,
    longitude: 6.7812,
    has_sorting_data: false,
    sorting_data_quality: 0,
    created_at: now(),
    updated_at: now(),
  },
  {
    store_id: "store-aldi-schadow",
    name: "ALDI SÜD Schadowstraße",
    address: "Schadowstraße 42, 40212 Düsseldorf",
    city: "Düsseldorf",
    postal_code: "40212",
    country: "DE",
    latitude: 51.2245,
    longitude: 6.7820,
    has_sorting_data: false,
    sorting_data_quality: 0,
    created_at: now(),
    updated_at: now(),
  },
];

function norm(s: string): string {
  return s
    .toLowerCase()
    .replace(/[äöüß]/g, (c) => ({ ä: "a", ö: "o", ü: "u", ß: "ss" }[c] ?? c))
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export const SEED_PRODUCTS: Product[] = [
  // Milchprodukte
  {
    product_id: "prod-milsani-fettarm",
    name: "Milsani Fettarme Milch 1,5% 1L",
    name_normalized: norm("Milsani Fettarme Milch 1,5% 1L"),
    brand: "Milsani",
    category_id: "cat-milch",
    price: 0.99,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-milsani-vollmilch",
    name: "Milsani Frische Vollmilch 3,5% 1L",
    name_normalized: norm("Milsani Frische Vollmilch 3,5% 1L"),
    brand: "Milsani",
    category_id: "cat-milch",
    price: 1.09,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-milsani-h-15",
    name: "Milsani H-Milch 1,5% 1L",
    name_normalized: norm("Milsani H-Milch 1,5% 1L"),
    brand: "Milsani",
    category_id: "cat-milch",
    price: 0.85,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-milsani-h-35",
    name: "Milsani H-Milch 3,5% 1L",
    name_normalized: norm("Milsani H-Milch 3,5% 1L"),
    brand: "Milsani",
    category_id: "cat-milch",
    price: 0.95,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-milka-alpenmilch",
    name: "Milka Schokolade Alpenmilch 100g",
    name_normalized: norm("Milka Schokolade Alpenmilch 100g"),
    brand: "Milka",
    category_id: "cat-suess",
    price: 1.19,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-butter",
    name: "Südfeld Butter 250g",
    name_normalized: norm("Südfeld Butter 250g"),
    brand: "Südfeld",
    category_id: "cat-milch",
    price: 1.49,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-gouda",
    name: "Gouda jung 200g",
    name_normalized: norm("Gouda jung 200g"),
    brand: null,
    category_id: "cat-milch",
    price: 1.79,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  // Obst & Gemüse
  {
    product_id: "prod-aepfel",
    name: "Äpfel Granny Smith 1kg",
    name_normalized: norm("Äpfel Granny Smith 1kg"),
    brand: null,
    category_id: "cat-obst-gemuese",
    price: 1.99,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-bananen",
    name: "Bananen 1kg",
    name_normalized: norm("Bananen 1kg"),
    brand: null,
    category_id: "cat-obst-gemuese",
    price: 1.29,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-tomaten",
    name: "Tomaten Stück 500g",
    name_normalized: norm("Tomaten Stück 500g"),
    brand: null,
    category_id: "cat-obst-gemuese",
    price: 1.49,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  // Tiefkühl
  {
    product_id: "prod-pizza-margherita",
    name: "Pizza Margherita 390g",
    name_normalized: norm("Pizza Margherita 390g"),
    brand: null,
    category_id: "cat-tiefkuehl",
    price: 2.29,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-pommes",
    name: "Pommes Frites 600g",
    name_normalized: norm("Pommes Frites 600g"),
    brand: null,
    category_id: "cat-tiefkuehl",
    price: 1.49,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  // Brot
  {
    product_id: "prod-vollkornbrot",
    name: "Vollkornbrot 500g",
    name_normalized: norm("Vollkornbrot 500g"),
    brand: null,
    category_id: "cat-brot",
    price: 1.19,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  // Getränke
  {
    product_id: "prod-mineralwasser",
    name: "Mineralwasser still 1,5L",
    name_normalized: norm("Mineralwasser still 1,5L"),
    brand: null,
    category_id: "cat-getraenke",
    price: 0.29,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-apfelsaft",
    name: "Apfelsaft 1L",
    name_normalized: norm("Apfelsaft 1L"),
    brand: null,
    category_id: "cat-getraenke",
    price: 0.99,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  // Grundnahrung
  {
    product_id: "prod-nudeln",
    name: "Spaghetti 500g",
    name_normalized: norm("Spaghetti 500g"),
    brand: null,
    category_id: "cat-grundnahrung",
    price: 0.49,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    product_id: "prod-reis",
    name: "Reis Langkorn 1kg",
    name_normalized: norm("Reis Langkorn 1kg"),
    brand: null,
    category_id: "cat-grundnahrung",
    price: 1.29,
    price_updated_at: now(),
    assortment_type: "daily_range",
    availability: "national",
    region: null,
    country: "DE",
    special_start_date: null,
    special_end_date: null,
    status: "active",
    source: "admin",
    crowdsource_status: null,
    created_at: now(),
    updated_at: now(),
  },
];
