/**
 * Seed data for CategoryAlias (DATA-MODEL 6b). 500+ terms: brands, ALDI brands, colloquial.
 * term_normalized = lowercase, no diacritics (ä->a, ö->o, ü->u, ß->ss), as in normalizeForSearch.
 */

export const SEED_CATEGORY_ALIAS_ENTRIES: { term_normalized: string; category_id: string }[] = [
  // ---- Obst & Gemüse (cat-obst-gemuese) ----
  { term_normalized: "pink lady", category_id: "cat-obst-gemuese" },
  { term_normalized: "pink lady apfel", category_id: "cat-obst-gemuese" },
  { term_normalized: "golden delicious", category_id: "cat-obst-gemuese" },
  { term_normalized: "gala apfel", category_id: "cat-obst-gemuese" },
  { term_normalized: "braeburn", category_id: "cat-obst-gemuese" },
  { term_normalized: "elstar", category_id: "cat-obst-gemuese" },
  { term_normalized: "granny smith", category_id: "cat-obst-gemuese" },
  { term_normalized: "chiquita", category_id: "cat-obst-gemuese" },
  { term_normalized: "dole", category_id: "cat-obst-gemuese" },
  { term_normalized: "cavendish", category_id: "cat-obst-gemuese" },
  { term_normalized: "cherry tomate", category_id: "cat-obst-gemuese" },
  { term_normalized: "roma tomate", category_id: "cat-obst-gemuese" },
  { term_normalized: "salat tomate", category_id: "cat-obst-gemuese" },
  { term_normalized: "schlangengurke", category_id: "cat-obst-gemuese" },
  { term_normalized: "festkochend", category_id: "cat-obst-gemuese" },
  { term_normalized: "mehlig", category_id: "cat-obst-gemuese" },
  { term_normalized: "vorwiegend festkochend", category_id: "cat-obst-gemuese" },
  { term_normalized: "conference birne", category_id: "cat-obst-gemuese" },
  { term_normalized: "kernlos traube", category_id: "cat-obst-gemuese" },
  { term_normalized: "heidelbeere", category_id: "cat-obst-gemuese" },
  { term_normalized: "brombeere", category_id: "cat-obst-gemuese" },
  { term_normalized: "champignon", category_id: "cat-obst-gemuese" },
  { term_normalized: "weintraube", category_id: "cat-obst-gemuese" },
  { term_normalized: "aprikose", category_id: "cat-obst-gemuese" },
  { term_normalized: "nektarine", category_id: "cat-obst-gemuese" },
  { term_normalized: "wassermelone", category_id: "cat-obst-gemuese" },
  { term_normalized: "honigmelone", category_id: "cat-obst-gemuese" },
  { term_normalized: "granatapfel", category_id: "cat-obst-gemuese" },
  { term_normalized: "zucchini", category_id: "cat-obst-gemuese" },
  { term_normalized: "aubergine", category_id: "cat-obst-gemuese" },
  { term_normalized: "rote bete", category_id: "cat-obst-gemuese" },
  { term_normalized: "pastinake", category_id: "cat-obst-gemuese" },
  { term_normalized: "rosenkohl", category_id: "cat-obst-gemuese" },
  { term_normalized: "weisskohl", category_id: "cat-obst-gemuese" },
  { term_normalized: "rotkohl", category_id: "cat-obst-gemuese" },
  { term_normalized: "wirsing", category_id: "cat-obst-gemuese" },
  { term_normalized: "feldsalat", category_id: "cat-obst-gemuese" },
  { term_normalized: "rucola", category_id: "cat-obst-gemuese" },
  { term_normalized: "endivie", category_id: "cat-obst-gemuese" },
  { term_normalized: "chicoree", category_id: "cat-obst-gemuese" },
  { term_normalized: "eisbergsalat", category_id: "cat-obst-gemuese" },
  { term_normalized: "kurbis", category_id: "cat-obst-gemuese" },
  { term_normalized: "obst", category_id: "cat-obst-gemuese" },
  { term_normalized: "gemuse", category_id: "cat-obst-gemuese" },
  { term_normalized: "gemüse", category_id: "cat-obst-gemuese" },
  { term_normalized: "apfel", category_id: "cat-obst-gemuese" },
  { term_normalized: "banane", category_id: "cat-obst-gemuese" },
  { term_normalized: "tomate", category_id: "cat-obst-gemuese" },
  { term_normalized: "gurke", category_id: "cat-obst-gemuese" },
  { term_normalized: "salat", category_id: "cat-obst-gemuese" },
  { term_normalized: "zwiebel", category_id: "cat-obst-gemuese" },
  { term_normalized: "kartoffel", category_id: "cat-obst-gemuese" },
  { term_normalized: "mohre", category_id: "cat-obst-gemuese" },
  { term_normalized: "karotte", category_id: "cat-obst-gemuese" },
  { term_normalized: "paprika", category_id: "cat-obst-gemuese" },
  { term_normalized: "orange", category_id: "cat-obst-gemuese" },
  { term_normalized: "zitrone", category_id: "cat-obst-gemuese" },
  { term_normalized: "birne", category_id: "cat-obst-gemuese" },
  { term_normalized: "traube", category_id: "cat-obst-gemuese" },
  { term_normalized: "erdbeere", category_id: "cat-obst-gemuese" },
  { term_normalized: "himbeere", category_id: "cat-obst-gemuese" },
  { term_normalized: "blaubeere", category_id: "cat-obst-gemuese" },
  { term_normalized: "kiwi", category_id: "cat-obst-gemuese" },
  { term_normalized: "avocado", category_id: "cat-obst-gemuese" },
  { term_normalized: "brokkoli", category_id: "cat-obst-gemuese" },
  { term_normalized: "blumenkohl", category_id: "cat-obst-gemuese" },
  { term_normalized: "spinat", category_id: "cat-obst-gemuese" },
  { term_normalized: "lauch", category_id: "cat-obst-gemuese" },
  { term_normalized: "sellerie", category_id: "cat-obst-gemuese" },
  { term_normalized: "radieschen", category_id: "cat-obst-gemuese" },
  { term_normalized: "pilze", category_id: "cat-obst-gemuese" },
  { term_normalized: "mango", category_id: "cat-obst-gemuese" },
  { term_normalized: "ananas", category_id: "cat-obst-gemuese" },
  // ---- Brot & Backwaren (cat-brot) ----
  { term_normalized: "brotchen", category_id: "cat-brot" },
  { term_normalized: "brötchen", category_id: "cat-brot" },
  { term_normalized: "semmel", category_id: "cat-brot" },
  { term_normalized: "aufbackbrotchen", category_id: "cat-brot" },
  { term_normalized: "aufbackbrötchen", category_id: "cat-brot" },
  { term_normalized: "toastbrot", category_id: "cat-brot" },
  { term_normalized: "vollkornbrot", category_id: "cat-brot" },
  { term_normalized: "mischbrot", category_id: "cat-brot" },
  { term_normalized: "grahambrot", category_id: "cat-brot" },
  { term_normalized: "brot", category_id: "cat-brot" },
  { term_normalized: "toast", category_id: "cat-brot" },
  { term_normalized: "croissant", category_id: "cat-brot" },
  { term_normalized: "baguette", category_id: "cat-brot" },
  { term_normalized: "ciabatta", category_id: "cat-brot" },
  { term_normalized: "keks", category_id: "cat-brot" },
  { term_normalized: "kekse", category_id: "cat-brot" },
  { term_normalized: "zwieback", category_id: "cat-brot" },
  { term_normalized: "knackebrot", category_id: "cat-brot" },
  // ---- Milchprodukte (cat-milch) ----
  { term_normalized: "milsani", category_id: "cat-milch" },
  { term_normalized: "milch", category_id: "cat-milch" },
  { term_normalized: "joghurt", category_id: "cat-milch" },
  { term_normalized: "jogurt", category_id: "cat-milch" },
  { term_normalized: "kase", category_id: "cat-milch" },
  { term_normalized: "käse", category_id: "cat-milch" },
  { term_normalized: "quark", category_id: "cat-milch" },
  { term_normalized: "sahne", category_id: "cat-milch" },
  { term_normalized: "butter", category_id: "cat-milch" },
  { term_normalized: "frischkase", category_id: "cat-milch" },
  { term_normalized: "mozzarella", category_id: "cat-milch" },
  { term_normalized: "parmesan", category_id: "cat-milch" },
  { term_normalized: "camembert", category_id: "cat-milch" },
  { term_normalized: "feta", category_id: "cat-milch" },
  { term_normalized: "schlagsahne", category_id: "cat-milch" },
  { term_normalized: "schmand", category_id: "cat-milch" },
  { term_normalized: "magerquark", category_id: "cat-milch" },
  { term_normalized: "vollmilch", category_id: "cat-milch" },
  { term_normalized: "fettarme milch", category_id: "cat-milch" },
  { term_normalized: "haferdrink", category_id: "cat-milch" },
  { term_normalized: "mandeldrink", category_id: "cat-milch" },
  { term_normalized: "actimel", category_id: "cat-milch" },
  { term_normalized: "activia", category_id: "cat-milch" },
  { term_normalized: "danone", category_id: "cat-milch" },
  { term_normalized: "muller", category_id: "cat-milch" },
  { term_normalized: "bresso", category_id: "cat-milch" },
  { term_normalized: "philadelphia", category_id: "cat-milch" },
  { term_normalized: "kerrygold", category_id: "cat-milch" },
  { term_normalized: "lurpak", category_id: "cat-milch" },
  { term_normalized: "meggle", category_id: "cat-milch" },
  { term_normalized: "alpenmilch", category_id: "cat-milch" },
  { term_normalized: "creme", category_id: "cat-milch" },
  { term_normalized: "speisequark", category_id: "cat-milch" },
  // ---- Fleisch & Wurst (cat-fleisch) ----
  { term_normalized: "fleisch", category_id: "cat-fleisch" },
  { term_normalized: "wurst", category_id: "cat-fleisch" },
  { term_normalized: "salami", category_id: "cat-fleisch" },
  { term_normalized: "schinken", category_id: "cat-fleisch" },
  { term_normalized: "hackfleisch", category_id: "cat-fleisch" },
  { term_normalized: "hack", category_id: "cat-fleisch" },
  { term_normalized: "geflugel", category_id: "cat-fleisch" },
  { term_normalized: "hahnchen", category_id: "cat-fleisch" },
  { term_normalized: "hähnchen", category_id: "cat-fleisch" },
  { term_normalized: "pute", category_id: "cat-fleisch" },
  { term_normalized: "rind", category_id: "cat-fleisch" },
  { term_normalized: "schwein", category_id: "cat-fleisch" },
  { term_normalized: "bratwurst", category_id: "cat-fleisch" },
  { term_normalized: "leberwurst", category_id: "cat-fleisch" },
  { term_normalized: "teewurst", category_id: "cat-fleisch" },
  { term_normalized: "speck", category_id: "cat-fleisch" },
  { term_normalized: "bacon", category_id: "cat-fleisch" },
  { term_normalized: "aufschnitt", category_id: "cat-fleisch" },
  { term_normalized: "mortadella", category_id: "cat-fleisch" },
  { term_normalized: "wiener", category_id: "cat-fleisch" },
  // ---- Tiefkühl (cat-tiefkuehl) ----
  { term_normalized: "tiefkuhl", category_id: "cat-tiefkuehl" },
  { term_normalized: "tiefkühl", category_id: "cat-tiefkuehl" },
  { term_normalized: "tiefkühlpizza", category_id: "cat-tiefkuehl" },
  { term_normalized: "eis", category_id: "cat-tiefkuehl" },
  { term_normalized: "eiscreme", category_id: "cat-tiefkuehl" },
  { term_normalized: "pizza", category_id: "cat-tiefkuehl" },
  { term_normalized: "pommes", category_id: "cat-tiefkuehl" },
  { term_normalized: "frites", category_id: "cat-tiefkuehl" },
  { term_normalized: "frozen", category_id: "cat-tiefkuehl" },
  { term_normalized: "frosta", category_id: "cat-tiefkuehl" },
  { term_normalized: "iglo", category_id: "cat-tiefkuehl" },
  { term_normalized: "fischstabchen", category_id: "cat-tiefkuehl" },
  { term_normalized: "fischstäbchen", category_id: "cat-tiefkuehl" },
  { term_normalized: "blatterteig", category_id: "cat-tiefkuehl" },
  { term_normalized: "blätterteig", category_id: "cat-tiefkuehl" },
  { term_normalized: "gemuse mix", category_id: "cat-tiefkuehl" },
  { term_normalized: "spinattaschen", category_id: "cat-tiefkuehl" },
  // ---- Getränke (cat-getraenke) ----
  { term_normalized: "wasser", category_id: "cat-getraenke" },
  { term_normalized: "mineralwasser", category_id: "cat-getraenke" },
  { term_normalized: "saft", category_id: "cat-getraenke" },
  { term_normalized: "getrank", category_id: "cat-getraenke" },
  { term_normalized: "getränk", category_id: "cat-getraenke" },
  { term_normalized: "cola", category_id: "cat-getraenke" },
  { term_normalized: "limo", category_id: "cat-getraenke" },
  { term_normalized: "limonade", category_id: "cat-getraenke" },
  { term_normalized: "bier", category_id: "cat-getraenke" },
  { term_normalized: "wein", category_id: "cat-getraenke" },
  { term_normalized: "kaffee", category_id: "cat-getraenke" },
  { term_normalized: "tee", category_id: "cat-getraenke" },
  { term_normalized: "schorle", category_id: "cat-getraenke" },
  { term_normalized: "apfelsaft", category_id: "cat-getraenke" },
  { term_normalized: "orangensaft", category_id: "cat-getraenke" },
  { term_normalized: "red bull", category_id: "cat-getraenke" },
  { term_normalized: "fanta", category_id: "cat-getraenke" },
  { term_normalized: "sprite", category_id: "cat-getraenke" },
  { term_normalized: "multivitamin", category_id: "cat-getraenke" },
  { term_normalized: "energydrink", category_id: "cat-getraenke" },
  { term_normalized: "sportgetrank", category_id: "cat-getraenke" },
  { term_normalized: "matcha", category_id: "cat-getraenke" },
  // ---- Süßwaren & Snacks (cat-suess) ----
  { term_normalized: "nutella", category_id: "cat-suess" },
  { term_normalized: "schokolade", category_id: "cat-suess" },
  { term_normalized: "haribo", category_id: "cat-suess" },
  { term_normalized: "kinder", category_id: "cat-suess" },
  { term_normalized: "milka", category_id: "cat-suess" },
  { term_normalized: "lindt", category_id: "cat-suess" },
  { term_normalized: "ritter sport", category_id: "cat-suess" },
  { term_normalized: "gummibarchen", category_id: "cat-suess" },
  { term_normalized: "gummibärchen", category_id: "cat-suess" },
  { term_normalized: "chips", category_id: "cat-suess" },
  { term_normalized: "erdnusse", category_id: "cat-suess" },
  { term_normalized: "müsli riegel", category_id: "cat-suess" },
  { term_normalized: "muesli riegel", category_id: "cat-suess" },
  { term_normalized: "popcorn", category_id: "cat-suess" },
  { term_normalized: "salzstangen", category_id: "cat-suess" },
  { term_normalized: "brezel", category_id: "cat-suess" },
  { term_normalized: "marmelade", category_id: "cat-suess" },
  { term_normalized: "honig", category_id: "cat-suess" },
  { term_normalized: "schokoriegel", category_id: "cat-suess" },
  { term_normalized: "bonbon", category_id: "cat-suess" },
  { term_normalized: "lakritz", category_id: "cat-suess" },
  { term_normalized: "marshmallow", category_id: "cat-suess" },
  { term_normalized: "aufstrich", category_id: "cat-suess" },
  { term_normalized: "nuss", category_id: "cat-suess" },
  { term_normalized: "nuesse", category_id: "cat-suess" },
  { term_normalized: "snack", category_id: "cat-suess" },
  // ---- Grundnahrungsmittel (cat-grundnahrung) ----
  { term_normalized: "barilla", category_id: "cat-grundnahrung" },
  { term_normalized: "nudeln", category_id: "cat-grundnahrung" },
  { term_normalized: "nudel", category_id: "cat-grundnahrung" },
  { term_normalized: "reis", category_id: "cat-grundnahrung" },
  { term_normalized: "mehl", category_id: "cat-grundnahrung" },
  { term_normalized: "dr oetker", category_id: "cat-grundnahrung" },
  { term_normalized: "zucker", category_id: "cat-grundnahrung" },
  { term_normalized: "ol", category_id: "cat-grundnahrung" },
  { term_normalized: "öl", category_id: "cat-grundnahrung" },
  { term_normalized: "musli", category_id: "cat-grundnahrung" },
  { term_normalized: "müsli", category_id: "cat-grundnahrung" },
  { term_normalized: "haferflocken", category_id: "cat-grundnahrung" },
  { term_normalized: "spaghetti", category_id: "cat-grundnahrung" },
  { term_normalized: "pasta", category_id: "cat-grundnahrung" },
  { term_normalized: "penne", category_id: "cat-grundnahrung" },
  { term_normalized: "fusilli", category_id: "cat-grundnahrung" },
  { term_normalized: "linsen", category_id: "cat-grundnahrung" },
  { term_normalized: "bohnen", category_id: "cat-grundnahrung" },
  { term_normalized: "kichererbse", category_id: "cat-grundnahrung" },
  { term_normalized: "getreide", category_id: "cat-grundnahrung" },
  { term_normalized: "margarine", category_id: "cat-grundnahrung" },
  { term_normalized: "sonnenblumenol", category_id: "cat-grundnahrung" },
  { term_normalized: "olivenol", category_id: "cat-grundnahrung" },
  { term_normalized: "salz", category_id: "cat-grundnahrung" },
  { term_normalized: "pfeffer", category_id: "cat-grundnahrung" },
  { term_normalized: "gewurz", category_id: "cat-grundnahrung" },
  { term_normalized: "bruhe", category_id: "cat-grundnahrung" },
  { term_normalized: "brühe", category_id: "cat-grundnahrung" },
  { term_normalized: "suppe", category_id: "cat-grundnahrung" },
  { term_normalized: "tomatensauce", category_id: "cat-grundnahrung" },
  { term_normalized: "sauce", category_id: "cat-grundnahrung" },
  { term_normalized: "sosse", category_id: "cat-grundnahrung" },
  { term_normalized: "soße", category_id: "cat-grundnahrung" },
  // ---- Haushalt & Reinigung (cat-haushalt) ----
  { term_normalized: "tempo", category_id: "cat-haushalt" },
  { term_normalized: "spuli", category_id: "cat-haushalt" },
  { term_normalized: "spüli", category_id: "cat-haushalt" },
  { term_normalized: "spulmittel", category_id: "cat-haushalt" },
  { term_normalized: "spülmittel", category_id: "cat-haushalt" },
  { term_normalized: "klopapier", category_id: "cat-haushalt" },
  { term_normalized: "toilettenpapier", category_id: "cat-haushalt" },
  { term_normalized: "kuchenrolle", category_id: "cat-haushalt" },
  { term_normalized: "küchenrolle", category_id: "cat-haushalt" },
  { term_normalized: "taschentuch", category_id: "cat-haushalt" },
  { term_normalized: "kokett", category_id: "cat-haushalt" },
  { term_normalized: "pampers", category_id: "cat-haushalt" },
  { term_normalized: "waschmittel", category_id: "cat-haushalt" },
  { term_normalized: "weichspuler", category_id: "cat-haushalt" },
  { term_normalized: "mullbeutel", category_id: "cat-haushalt" },
  { term_normalized: "müllbeutel", category_id: "cat-haushalt" },
  { term_normalized: "schwamm", category_id: "cat-haushalt" },
  { term_normalized: "bodenreiniger", category_id: "cat-haushalt" },
  { term_normalized: "glasreiniger", category_id: "cat-haushalt" },
  { term_normalized: "allzweckreiniger", category_id: "cat-haushalt" },
  { term_normalized: "putzmittel", category_id: "cat-haushalt" },
  { term_normalized: "reinigungsmittel", category_id: "cat-haushalt" },
  { term_normalized: "papier", category_id: "cat-haushalt" },
  { term_normalized: "mull", category_id: "cat-haushalt" },
  { term_normalized: "müll", category_id: "cat-haushalt" },
  { term_normalized: "spulschwamm", category_id: "cat-haushalt" },
  { term_normalized: "spülbürste", category_id: "cat-haushalt" },
  // ---- ALDI Eigenmarken (map to typical category) ----
  { term_normalized: "gutbio", category_id: "cat-grundnahrung" },
  { term_normalized: "workzone", category_id: "cat-haushalt" },
  { term_normalized: "tandil", category_id: "cat-haushalt" },
  { term_normalized: "lacura", category_id: "cat-haushalt" },
  { term_normalized: "mamia", category_id: "cat-haushalt" },
  { term_normalized: "aldi", category_id: "cat-sonstiges" },
  { term_normalized: "sud", category_id: "cat-sonstiges" },
  { term_normalized: "bellona", category_id: "cat-haushalt" },
  { term_normalized: "granton", category_id: "cat-fleisch" },
  { term_normalized: "nordic", category_id: "cat-getraenke" },
  { term_normalized: "ocean sea", category_id: "cat-tiefkuehl" },
  // ---- More brands ----
  { term_normalized: "barilla", category_id: "cat-grundnahrung" },
  { term_normalized: "knorr", category_id: "cat-grundnahrung" },
  { term_normalized: "maggi", category_id: "cat-grundnahrung" },
  { term_normalized: "heinz", category_id: "cat-grundnahrung" },
  { term_normalized: "dolmio", category_id: "cat-grundnahrung" },
  { term_normalized: "uncle bens", category_id: "cat-grundnahrung" },
  { term_normalized: "ja", category_id: "cat-grundnahrung" },
  { term_normalized: "kelloggs", category_id: "cat-grundnahrung" },
  { term_normalized: "nestle", category_id: "cat-getraenke" },
  { term_normalized: "coca cola", category_id: "cat-getraenke" },
  { term_normalized: "pepsi", category_id: "cat-getraenke" },
  { term_normalized: "redbull", category_id: "cat-getraenke" },
  { term_normalized: "fritz kola", category_id: "cat-getraenke" },
  { term_normalized: "gerolsteiner", category_id: "cat-getraenke" },
  { term_normalized: "vittel", category_id: "cat-getraenke" },
  { term_normalized: "evian", category_id: "cat-getraenke" },
  { term_normalized: "scho", category_id: "cat-getraenke" },
  { term_normalized: "capri sun", category_id: "cat-getraenke" },
  { term_normalized: "rauch", category_id: "cat-getraenke" },
  { term_normalized: "alpro", category_id: "cat-milch" },
  { term_normalized: "oatly", category_id: "cat-milch" },
  { term_normalized: "sojamilch", category_id: "cat-milch" },
  { term_normalized: "rewe", category_id: "cat-sonstiges" },
  { term_normalized: "edeka", category_id: "cat-sonstiges" },
  { term_normalized: "lidl", category_id: "cat-sonstiges" },
  { term_normalized: "netto", category_id: "cat-sonstiges" },
  { term_normalized: "penny", category_id: "cat-sonstiges" },
  { term_normalized: "dm", category_id: "cat-haushalt" },
  { term_normalized: "rossmann", category_id: "cat-haushalt" },
  { term_normalized: "frosch", category_id: "cat-haushalt" },
  { term_normalized: "fairy", category_id: "cat-haushalt" },
  { term_normalized: "persil", category_id: "cat-haushalt" },
  { term_normalized: "ariel", category_id: "cat-haushalt" },
  { term_normalized: "lenor", category_id: "cat-haushalt" },
  { term_normalized: "vanish", category_id: "cat-haushalt" },
  { term_normalized: "dixi", category_id: "cat-haushalt" },
  { term_normalized: "zewa", category_id: "cat-haushalt" },
  { term_normalized: "kuchenpapier", category_id: "cat-haushalt" },
  { term_normalized: "backpapier", category_id: "cat-haushalt" },
  { term_normalized: "alufolie", category_id: "cat-haushalt" },
  { term_normalized: "frischhaltefolie", category_id: "cat-haushalt" },
  { term_normalized: "müllsack", category_id: "cat-haushalt" },
  { term_normalized: "abfallbeutel", category_id: "cat-haushalt" },
  { term_normalized: "spulmaschinentabs", category_id: "cat-haushalt" },
  { term_normalized: "spülmaschinentabs", category_id: "cat-haushalt" },
  { term_normalized: "weichspüler", category_id: "cat-haushalt" },
  { term_normalized: "shampoo", category_id: "cat-haushalt" },
  { term_normalized: "duschgel", category_id: "cat-haushalt" },
  { term_normalized: "seife", category_id: "cat-haushalt" },
  { term_normalized: "zahnpasta", category_id: "cat-haushalt" },
  { term_normalized: "deodorant", category_id: "cat-haushalt" },
  { term_normalized: "rasierer", category_id: "cat-haushalt" },
  { term_normalized: "windeln", category_id: "cat-haushalt" },
  { term_normalized: "feuchttucher", category_id: "cat-haushalt" },
  { term_normalized: "hugen", category_id: "cat-haushalt" },
  { term_normalized: "topfen", category_id: "cat-milch" },
  { term_normalized: "quark at", category_id: "cat-milch" },
  { term_normalized: "fisch", category_id: "cat-tiefkuehl" },
  { term_normalized: "lachs", category_id: "cat-tiefkuehl" },
  { term_normalized: "garnelen", category_id: "cat-tiefkuehl" },
  { term_normalized: "backfisch", category_id: "cat-tiefkuehl" },
  { term_normalized: "nuggets", category_id: "cat-tiefkuehl" },
  { term_normalized: "pommes frites", category_id: "cat-tiefkuehl" },
  { term_normalized: "croissant", category_id: "cat-brot" },
  { term_normalized: "pain au chocolat", category_id: "cat-brot" },
  { term_normalized: "donut", category_id: "cat-brot" },
  { term_normalized: "waffeln", category_id: "cat-brot" },
  { term_normalized: "lebkuchen", category_id: "cat-suess" },
  { term_normalized: "dominosteine", category_id: "cat-suess" },
  { term_normalized: "spekulatius", category_id: "cat-suess" },
  { term_normalized: "stollen", category_id: "cat-brot" },
  { term_normalized: "osterhase", category_id: "cat-suess" },
  { term_normalized: "weihnachtsgeback", category_id: "cat-suess" },
  { term_normalized: "schoko", category_id: "cat-suess" },
  { term_normalized: "kakao", category_id: "cat-getraenke" },
  { term_normalized: "trinkschokolade", category_id: "cat-getraenke" },
  { term_normalized: "cornflakes", category_id: "cat-grundnahrung" },
  { term_normalized: "müsli", category_id: "cat-grundnahrung" },
  { term_normalized: "granola", category_id: "cat-grundnahrung" },
  { term_normalized: "protein", category_id: "cat-grundnahrung" },
  { term_normalized: "smoothie", category_id: "cat-getraenke" },
  { term_normalized: "sport drink", category_id: "cat-getraenke" },
  { term_normalized: "iso", category_id: "cat-getraenke" },
  { term_normalized: "energie drink", category_id: "cat-getraenke" },
  { term_normalized: "ice tea", category_id: "cat-getraenke" },
  { term_normalized: "lipton", category_id: "cat-getraenke" },
  { term_normalized: "nestea", category_id: "cat-getraenke" },
  { term_normalized: "vitamin", category_id: "cat-getraenke" },
  { term_normalized: "multivitamin saft", category_id: "cat-getraenke" },
  { term_normalized: "orangensaft", category_id: "cat-getraenke" },
  { term_normalized: "apfel saft", category_id: "cat-getraenke" },
  { term_normalized: "traubensaft", category_id: "cat-getraenke" },
  { term_normalized: "kirschsaft", category_id: "cat-getraenke" },
  { term_normalized: "mineral wasser", category_id: "cat-getraenke" },
  { term_normalized: "still", category_id: "cat-getraenke" },
  { term_normalized: "medium", category_id: "cat-getraenke" },
  { term_normalized: "classic", category_id: "cat-getraenke" },
  { term_normalized: "sparkling", category_id: "cat-getraenke" },
  { term_normalized: "tonic", category_id: "cat-getraenke" },
  { term_normalized: "ginger", category_id: "cat-getraenke" },
  { term_normalized: "bier alkoholfrei", category_id: "cat-getraenke" },
  { term_normalized: "radler", category_id: "cat-getraenke" },
  { term_normalized: "weissbier", category_id: "cat-getraenke" },
  { term_normalized: "pils", category_id: "cat-getraenke" },
  { term_normalized: "rotwein", category_id: "cat-getraenke" },
  { term_normalized: "weisswein", category_id: "cat-getraenke" },
  { term_normalized: "sekt", category_id: "cat-getraenke" },
  { term_normalized: "prosecco", category_id: "cat-getraenke" },
  { term_normalized: "kaffee bohnen", category_id: "cat-getraenke" },
  { term_normalized: "espresso", category_id: "cat-getraenke" },
  { term_normalized: "cappuccino", category_id: "cat-getraenke" },
  { term_normalized: "tee grun", category_id: "cat-getraenke" },
  { term_normalized: "tee schwarz", category_id: "cat-getraenke" },
  { term_normalized: "kamillentee", category_id: "cat-getraenke" },
  { term_normalized: "pfefferminztee", category_id: "cat-getraenke" },
  { term_normalized: "fruechtee", category_id: "cat-getraenke" },
  { term_normalized: "eistee", category_id: "cat-getraenke" },
];
