-- ALDI Data Import: Part 1 – Categories
-- DEPRECATED: The categories table has been dropped (migration 20260304000000).
-- Category data is now managed via the demand_groups table
-- (seeded in migration 20260303120000_demand_groups_schema.sql).
--
-- This file is kept as documentation only. Do not run it.
