/**
 * Official ALDI commodity groups (demand_group / demand_sub_group).
 * Source: products table — SELECT DISTINCT demand_group, demand_sub_group ORDER BY demand_group, demand_sub_group
 */

export interface DemandGroupOption {
  group: string;
  subGroups: string[];
}

export const DEMAND_GROUPS_LIST: DemandGroupOption[] = [
  { group: "01-Spirituosen", subGroups: ["01-Spirituosen", "02-Liköre/Bitter", "03-Mixgetränke"] },
  { group: "02-Sekt/Schaumwein", subGroups: ["01-Sekt/Schaumwein"] },
  { group: "03-Wein", subGroups: ["01-Rotwein", "02-Weißwein", "03-Roséwein", "04-Likör-/Dessertwein", "05-Weinhaltige Getränke/Weine, sortiert"] },
  { group: "04-Bier", subGroups: ["01-Bier", "02-Biergetränke"] },
  { group: "05-Wasser", subGroups: ["01-Wasser", "02-Wasser, aromatisiert"] },
  { group: "06-Wasch-/Putz-/Reinigungsmittel", subGroups: ["01-Waschmittel", "02-Waschhilfsmittel", "03-Spülmittel", "04-Putzmittel", "06-Lufterfrischer", "07-WC", "08-MGR (Maschinengeschirrreinigung)", "09-Autopflege"] },
  { group: "07-Kosmetik/Körperpflege", subGroups: ["01-Haarpflege/Accessoires", "02-Hautpflege", "06-Nagel-/Kosmetik Accessoires"] },
  { group: "08-Körperhygiene", subGroups: ["01-Waschen/Duschen/Baden", "02-Deodorants", "03-Zahn-/Mundhygiene", "04-Rasur/Haarentfernung", "05-Damenhygiene", "06-Inkontinenzprodukte"] },
  { group: "09-Babyartikel", subGroups: ["02-Beikost nass", "04-Pflegeprodukte", "06-Snacks/Getränke", "07-Windeln"] },
  { group: "10-Papierwaren", subGroups: ["01-Toilettenpapier", "02-Küchentücher", "03-Taschentücher/Kosmetiktücher", "04-Servietten/Geschirr"] },
  { group: "11-Folien/Tücher", subGroups: ["01-Haushaltsfolien", "02-Tragetaschen", "03-Reinigungstücher/Schwämme/Handschuhe"] },
  { group: "12-Audio/Video/Batterien", subGroups: ["02-Batterien/Akkus", "03-Datenträger, bespielt"] },
  { group: "13-Apothekenprodukte", subGroups: ["02-Wundversorgung/Hausapotheke", "03-Orale Arzneimittel", "04-Nahrungsergänzungsmittel", "06-Sportnahrung"] },
  { group: "14-Kinder-Textilien", subGroups: ["01-Unterwäsche", "02-Nachtwäsche", "04-Tops/Shirts/Pullover", "07-Socken, Strümpfe"] },
  { group: "15-Herren-Textilien", subGroups: ["01-Unterwäsche", "02-Nachtwäsche", "04-Shirts/Pullover", "05-Jacken/Westen", "07-Socken, Strümpfe"] },
  { group: "16-Damen-Textilien", subGroups: ["01-Unterwäsche", "02-Nachtwäsche", "03-Hosen", "04-Tops/Shirts/Pullover", "05-Jacken/Westen", "07-Socken, Feinstrümpfe", "09-Accessoires"] },
  { group: "17-Sport & Sportbekleidung", subGroups: ["02-Hosen", "06-Socken, Strümpfe", "07-Arbeits-/Berufsbekleidung"] },
  { group: "18-Heimtextilien", subGroups: ["01-Bettwäsche", "04-Bettwaren", "05-Frottierwaren", "06-Küchentextilien", "07-Teppiche/Badteppiche/Fußmatten", "08-Kissen/Kissenhüllen", "09-Decken"] },
  { group: "19-Möbel", subGroups: ["06-Badezimmermöbel"] },
  { group: "20-Unterhaltungselektronik", subGroups: ["01-TV", "02-Audio", "03-Foto/Kamera/Optik", "04-PCs/Hardware", "06-Telekommunikation", "07-Zubehör"] },
  { group: "22-Heimwerkerbedarf", subGroups: ["01-Elektrogeräte", "02-Zubehör für Elektrogeräte", "03-Handwerkzeuge", "04-Metallwaren/Befestigungsmaterial", "05-Leitern/Arbeitsvorrichtungen", "06-Farben/Lacke", "07-Malerzubehör", "08-Taschenlampen/Arbeitsleuchten", "09-Elektrozubehör", "10-Sanitär/Heizung/Klimatechnik", "11-Aufbewahrungssysteme", "12-Sicherheitsprodukte", "13-Rollen/Transporthilfen", "14-Sonstiger Werkstattbedarf"] },
  { group: "25-Haushaltsartikel", subGroups: ["01-Kerzen/Aromatherapie", "02-Aufbewahrungssysteme", "03-Koch-/Küchenzubehör", "04-Geschirr/Besteck", "05-Badzubehör", "07-Wäsche-/Waschzubehör", "08-Haushaltszubehör"] },
  { group: "27-Pflanzen/Blumen", subGroups: ["01-Schnittblumen", "02-Zimmerpflanzen", "03-Balkon-/Terrassenpflanzen", "04-Beetpflanzen", "06-Sträucher/Bäume/Stauden", "08-Saatgut/Anzucht", "09-Nahrungspflanzen"] },
  { group: "28-Schreibwaren/Büroartikel/Papeterie", subGroups: ["02-Schreib-/Malartikel", "04-Papierwaren", "07-Bürobedarf", "08-Bastelbedarf", "09-Handarbeit/Kurzwaren (Nähzubehör)"] },
  { group: "29-Deko-Artikel", subGroups: ["06-Seidenblumen/Kunstpflanzen"] },
  { group: "30-Koffer/Taschen", subGroups: ["01-Koffer", "03-Rucksäcke"] },
  { group: "31-Gartenbedarf", subGroups: ["01-Gartenmöbel", "02-Düngemittel/Pflanzenpflege", "03-Motorbetriebene Geräte", "04-Gartenwerkzeuge", "06-Blumentöpfe/Kübel", "08-Gartenzubehör", "09-Blumenerde", "10-Gartendekoration"] },
  { group: "32-Spielwaren", subGroups: ["01-Spielfiguren", "02-Spielzeugautos/-fahrzeuge", "07-Plüsch", "10-Kleinkinderspielzeug"] },
  { group: "33-Auto/Motorrad/Fahrrad", subGroups: ["01-Autozubehör"] },
  { group: "34-Sport/Camping/Freizeit", subGroups: ["01-Sportartikel Indoor", "02-Camping/Outdoor", "04-Grillen"] },
  { group: "35-Haushaltsgeräte", subGroups: ["01-Elektr. Haushaltsgeräte", "02-Elektr. Küchengeräte", "03-Elektr. Körperpflegegeräte", "04-Elektrogroßgeräte (weiße Ware)", "05-Med. Haushaltsgeräte"] },
  { group: "36-Schuhe", subGroups: ["06-Sportschuhe", "08-Hausschuhe"] },
  { group: "38-Gemüse", subGroups: ["01-Gemüse (hart)", "02-Paprika", "03-Tomaten", "04-Kohlgemüse", "05-Wurzel-/Knollengemüse", "06-Kartoffeln", "07-Zwiebelgemüse", "08-Pilze", "09-Hülsenfrüchte", "10-Kürbisse", "11-Zucchini", "12-Spargel", "13-Frische Kräuter", "14-Gewürze", "16-Sonstiges Gemüse", "17-Snacks/Gemüse, verzehrfertig"] },
  { group: "39-Tierbedarf", subGroups: ["02-Katzenzubehör"] },
  { group: "40-Bonbons/Kaugummi", subGroups: ["01-Kaugummi", "02-Bonbons (mit Zucker/zuckerfrei)", "03-Kaubonbons", "04-Fruchtgummi", "05-Lutschbonbons"] },
  { group: "41-Schokolade/Pralinen", subGroups: ["01-Tafelschokolade", "02-Schokoriegel", "03-Pralinen", "04-Süßwaren mit Schokolade"] },
  { group: "42-Gebäck", subGroups: ["01-Gebäck", "02-Waffeln"] },
  { group: "43-Saisonartikel Süßwaren", subGroups: ["01-Weihnachten", "02-Ostern"] },
  { group: "44-Salzgebäck", subGroups: ["01-Salzgebäck/Kräcker"] },
  { group: "45-Kaffee/Kakao", subGroups: ["01-Löslicher Kaffee", "02-Bohnenkaffee", "03-Kaffeehaltige Heißgetränke", "04-Pulvergetränke", "05-Kaffeekapseln", "06-Einzelportionen/Trinkfertig"] },
  { group: "46-Tee", subGroups: ["01-Kräutertee", "02-Schwarztee", "03-Instanttee", "04-Früchtetee", "06-Gemischte Sorten"] },
  { group: "47-Konserven", subGroups: ["01-Obstkonserven", "02-Gemüsekonserven", "03-Sauerkonserven", "04-Pilzkonserven", "06-Antipasti, ungekühlt"] },
  { group: "48-Fertiggerichte/Suppen", subGroups: ["01-Fertiggerichte", "02-Eintöpfe/Nasssuppen", "04-Instantgerichte", "05-Trockensuppen/Fixprodukte/trockene Suppe"] },
  { group: "49-Dauerwurst/Speck", subGroups: ["01-Dauerwurst/Speck"] },
  { group: "50-H-Milchprodukte/Milchersatzprodukte", subGroups: ["01-H-Käse", "02-H-Milch", "03-H-Sahne", "04-Milchersatzprodukte"] },
  { group: "51-Joghurts/Quark", subGroups: ["01-Joghurt, Natur", "02-Joghurt, Frucht", "03-Joghurtersatzprodukte", "04-Quark"] },
  { group: "52-Dressings/Öle/Soßen", subGroups: ["01-Ketchup/Senf", "02-Speiseöle", "03-Mayonnaise", "04-Soßen/Pesto", "05-Essig", "06-Dressings/Marinaden", "07-Meerrettich"] },
  { group: "53-Konfitüren/Brotaufstriche", subGroups: ["01-Fruchtaufstriche", "02-Honig", "03-Sirup/Garnierung", "04-Nussaufstriche", "05-Herzhafte Aufstriche", "06-Süße Aufstriche"] },
  { group: "54-Nährmittel", subGroups: ["01-Reis", "02-Teigwaren", "03-Kartoffelprodukte", "04-Kräuter/Gewürze/Würzzutaten", "06-Hülsenfrüchte/Getreide"] },
  { group: "55-Eier", subGroups: ["01-Rohe Eier", "02-Gekochte Eier"] },
  { group: "56-Bake-Off", subGroups: ["01-Weißbrot", "02-Schwarz-/Vollkornbrot", "03-Spezialbrot", "04-Pikante Snacks", "05-Feinbackwaren", "06-Brötchen/Semmeln"] },
  { group: "57-Brot/Kuchen", subGroups: ["01-Aufbackartikel", "02-Frischbrot", "03-Frische Feinbackwaren", "04-Frische Kleinbackwaren", "05-Haltbare Feinbackwaren", "06-Haltbarer Kuchen", "07-Haltbares Brot", "09-Brötchen/Semmeln", "10-Alternativen zum Sandwich", "11-Frischer Kuchen", "12-Kleingebäck"] },
  { group: "58-Obst", subGroups: ["01-Äpfel", "02-Birnen", "03-Steinobst", "04-Beeren", "05-Trauben", "06-Zitrusfrüchte", "07-Exotische Früchte", "08-Bananen", "10-Melonen", "11-Mangos", "12-Avocados", "15-Snacks/Obst, verzehrfertig"] },
  { group: "59-Tabakwaren", subGroups: ["01-Zigaretten", "02-Tabak", "03-Zubehör"] },
  { group: "60-Margarine/pflanzliche Fette", subGroups: ["01-Margarine/pflanzliche Fette"] },
  { group: "62-Frischfleisch (ohne Schwein/Geflügel)", subGroups: ["01-Rind, frisch", "02-Lamm, frisch", "03-Frischfleisch-Spezialitäten", "04-Hackfleisch, diverse"] },
  { group: "63-Geschenkkarten/Gutscheine/Tickets/Coupon", subGroups: ["02-Externe Geschenkkarten"] },
  { group: "64-Fisch, frisch", subGroups: ["01-Fisch", "02-Meeresfrüchte"] },
  { group: "67-Geflügel, frisch", subGroups: ["01-Hühnchen, frisch", "02-Pute, frisch", "04-Geflügelwaren-Spezialitäten, frisch", "05-Hackfleisch, Geflügel"] },
  { group: "68-Schweinefleisch, frisch", subGroups: ["01-Schwein, frisch", "05-Hackfleisch, Schwein"] },
  { group: "69-Gekühlte Wurstwaren", subGroups: ["01-Aspikware/Sülze", "02-Bratwurst", "03-Brühwurst", "04-Kochwurst", "05-Rohwurst", "06-Würstchen", "07-Schinken gekocht/gepökelt", "08-Schinken roh/gepökelt/luftgetrocknet", "09-Restliche Pökelware", "10-Sonstige Wurst", "11-Speck/Rohschinken", "12-Fleisch geschnitten/Wurst geschnitten", "13-Kochschinken", "15-Aufschnitt roh/gepökelt", "16-Gegarter Aufschnitt", "17-Pasteten", "18-Sonstige Fleischwaren"] },
  { group: "70-Gekühltes verzehrfertiges Fleisch/Fleisc", subGroups: ["02-Verzehrfertiges Fleisch", "04-Fleischersatzprodukte"] },
  { group: "71-Gekühlter verzehrfertiger Fisch", subGroups: ["01-Fisch/Meeresfrüchte"] },
  { group: "72-Gekühlte Fertiggerichte", subGroups: ["01-Fertiggerichte", "02-Pizza", "03-Kartoffelprodukte", "04-Teigwaren", "05-Backwaren"] },
  { group: "73-Gekühlte Feinkost", subGroups: ["01-Feinkost", "02-Aufstriche/Dips/Dressings", "04-Salat, verzehrfertig", "06-Sandwiches/Snacks", "07-Desserts"] },
  { group: "74-Gekühlte Getränke", subGroups: ["01-Säfte"] },
  { group: "75-TK Fleisch/Fisch", subGroups: ["01-Fisch/Meeresfrüchte", "02-Hühnchen", "03-Pute", "04-Schwein", "05-Rind", "07-Sonstige Fleischwaren", "10-Fleischersatzprodukte"] },
  { group: "76-TK Obst/Gemüse", subGroups: ["01-Gemüse", "02-Kartoffelprodukte", "03-Obst"] },
  { group: "77-TK Desserts/Backwaren/Eis", subGroups: ["01-Backwaren", "02-Eis", "03-Desserts/Mehlspeisen"] },
  { group: "78-TK Fertiggerichte/Pizzas", subGroups: ["01-Fertig-/Teilfertiggerichte", "02-Pizza/Baguettes", "03-Snacks/Kuchen"] },
  { group: "79-Funktionsgetränke/Eistee", subGroups: ["01-Sport-/Energy Drinks", "02-ACE", "03-Eistee"] },
  { group: "80-CO2 Erfrischungsgetränke", subGroups: ["01-Softdrinks/Fruchthaltige Erfrischungsget", "02-Tonics/Mixgetränke"] },
  { group: "81-Fruchtsäfte/Sirupe", subGroups: ["01-Fruchtsäfte (Säfte, Nektar)", "02-Sirupe"] },
  { group: "82-Wurst-/Fleisch-/Fischkonserven", subGroups: ["01-Fischkonserven", "02-Wurst-/Fleischkonserven"] },
  { group: "83-Milch/Sahne/Butter", subGroups: ["01-Milchgetränke", "02-Milch", "03-Sahne", "04-Butter/tierische Fette"] },
  { group: "84-Käse/Käseersatzprodukte", subGroups: ["01-Hart-/Schnittkäse", "02-Weichkäse", "03-Frischkäse", "04-Schmelzkäse", "05-Käseerzeugnisse eigener Art", "06-Cheddar am Stück", "07-Käse gerieben/zerkleinert", "09-Käse geschnitten", "10-Käsesnacks", "11-Käsespezialitäten"] },
  { group: "85-Tiernahrung", subGroups: ["01-Hundenahrung", "02-Katzennahrung", "03-Vogelnahrung"] },
  { group: "86-Chips/Snacks", subGroups: ["01-Chips", "02-Snacks"] },
  { group: "87-Nüsse/Trockenfrüchte", subGroups: ["01-Nüsse", "02-Trockenfrüchte"] },
  { group: "88-Salate", subGroups: ["01-Blattsalate", "02-Sonstige Salate"] },
  { group: "89-Backartikel", subGroups: ["01-Mehl", "02-Backzutaten", "03-Zucker/Süßungsmittel", "04-Dessertpulver", "05-Backmischungen"] },
  { group: "90-Cerealien/Snacks", subGroups: ["01-Cerealien", "02-Warme Cerealien/Haferbrei", "03-Snack-/Energie-/Müsliriegel"] },
  { group: "92-Beleuchtung", subGroups: ["02-Leuchtmittel", "03-Innenbeleuchtung"] },
  { group: "93-ALDI Services", subGroups: ["03-ALDI/HOFER Talk"] },
];
